name: Build and Release

on:
  push:
    tags:
      - 'v*' # Se activará para cualquier tag que comience con 'v'

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            asset_name: encriptar-linux
          - os: windows-latest
            asset_name: encriptar-windows
          - os: macos-latest
            asset_name: encriptar-macos

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build with PyInstaller
      run: pyinstaller --onefile encriptar.py

    - name: Rename and zip binary
      shell: pwsh
      run: |
        if ($env:RUNNER_OS -eq "Windows") {
          Move-Item dist\encriptar.exe dist\encriptar-windows.exe
          Compress-Archive -Path dist\encriptar-windows.exe -DestinationPath dist\encriptar-windows.zip
        } elseif ($env:RUNNER_OS -eq "Linux") {
          mv dist/encriptar dist/encriptar-linux
          cd dist && zip -j encriptar-linux.zip encriptar-linux
        } else {
          mv dist/encriptar dist/encriptar-macos
          cd dist && zip -j encriptar-macos.zip encriptar-macos
        }

    - name: Create source archives (Linux only)
      if: runner.os == 'Linux'
      run: |
        zip -j encriptar-source.zip encriptar.py requirements.txt
        tar -cvzf encriptar-source.tar.gz encriptar.py requirements.txt

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.asset_name }}.zip
        path: dist/${{ matrix.asset_name }}.zip
        compression-level: 0 # No compression as it's already zipped

    - name: Upload source archives (Linux only)
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v4
      with:
        name: source-archives
        path: |
          encriptar-source.zip
          encriptar-source.tar.gz
        compression-level: 0

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List downloaded artifacts
        run: |
          echo "Contents of artifacts directory:"
          ls -R artifacts

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: Encriptar ${{ github.ref_name }}
          files: |
            artifacts/**/*.zip
            artifacts/**/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}